apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sheshield.fullname" . }}-app
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ include "sheshield.name" . }}
    tier: frontend
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "sheshield.name" . }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: {{ include "sheshield.name" . }}
        tier: frontend
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.targetPort }}
          name: http
        env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: {{ include "sheshield.fullname" . }}-config
              key: db-host
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: {{ include "sheshield.fullname" . }}-config
              key: db-name
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: {{ include "sheshield.fullname" . }}-secrets
              key: db-user
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: {{ include "sheshield.fullname" . }}-secrets
              key: db-password
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        livenessProbe:
          {{- toYaml .Values.livenessProbe | nindent 10 }}
        readinessProbe:
          {{- toYaml .Values.readinessProbe | nindent 10 }}
