apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sheshield.fullname" . }}-secrets
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  db-user: {{ .Values.secrets.dbUser }}
  db-password: {{ .Values.secrets.dbPassword }}
